(use-modules (guix profiles)
             (gnu packages)
             (gnu packages freedesktop)
             (gnu packages pkg-config)
             (gnu packages xdisorg)
             (gnu packages xorg)
             (gnu packages zig-xyz)
             (gnu packages zig))

(packages->manifest
  (list
    (specification->package "zig")
    (specification->package "pkg-config")
    (specification->package "libinput")
    (specification->package "wayland")
    (specification->package "wayland-protocols")
    (specification->package "libxkbcommon")
    (specification->package "libevdev")
    (specification->package "pixman")
    (specification->package "wlroots")))
